version: '3'

services:
  mancala-backend:
    build:
      context: vladcares/mancala-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  mancala-frontend:
    build:
      context: vladcares/mancala-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mancala-backend
